### ISSUE TITLE
Update for Blender 2.8?

### ISSUE THREAD

**Issue by unfa** [Shahzod114/Bakelab-Blender-addon#2]
This add-on looks very promising, but I've already moved my workflow to Blender 2.8 - are there any plans on updating it so it'll work there too?

**Comment by specoolar** [comment]
Sorry for responding too late. I was too busy with other works. Now i came back to this project. New version coming soon

**Comment by specoolar** [comment]
Released new version
https://github.com/Shahzod114/Blender-BakeLab2
